Nikopeshe.WebApplication/Controllers/BranchController.cs
using Crosscutting.NetFramework.Logging;
using Nikopeshe.Data;
using Nikopeshe.Entity.DataModels;
using Nikopeshe.Infrastructure.Datatables;
using Nikopeshe.Services.Interfaces;
using Nikopeshe.WebApplication.Attributes;
using Nikopeshe.WebApplication.Extensions;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.ServiceModel;
using System.Web.Mvc;

namespace Nikopeshe.WebApplication.Controllers
{
    [Authorize(Roles = "Administrator")]
    [ExcludeFilter(typeof(AuthorizeIPAddressAttribute))]
    public class BranchController : BaseController
    {
        private readonly IBranchService branchservice;
        ServiceHeader serviceHeader = CustomHeaderUtility.ReadHeader(OperationContext.Current);
        public BranchController(IBranchService _branchservice)
        {
            if (_branchservice == null)
                throw new ArgumentNullException("service cannot be null.");

            this.branchservice = _branchservice;
        }

        // GET: Branch
        public ActionResult Index()
        {            
            return View();
        }

        public JsonResult GetAllBranches(JQueryDataTablesModel datatablemodel)
        {
            var pagecollection = branchservice.GetAllBranches();

            int totalRecordCount = 0;

            int searchRecordCount = 0;

            var _brancheslist = GetAllC2BTransactions(startIndex: datatablemodel.iDisplayStart,
                pageSize: datatablemodel.iDisplayLength, sortedColumns: datatablemodel.GetSortedColumns(),
                totalRecordCount: out totalRecordCount, searchRecordCount: out searchRecordCount, searchString: datatablemodel.sSearch, brancheslist: pagecollection);


            return Json(new JQueryDataTablesResponse<Branch>(items: _brancheslist,
                totalRecords: totalRecordCount,
                totalDisplayRecords: searchRecordCount,
                sEcho: datatablemodel.sEcho));
        }

        public IList<Branch> GetAllC2BTransactions(int startIndex, int pageSize, ReadOnlyCollection<SortedColumn> sortedColumns, out int totalRecordCount, out int searchRecordCount, string searchString, IList<Branch> brancheslist)
        {
            var _brancheslist = brancheslist;

            totalRecordCount = _brancheslist.Count();

            if (!string.IsNullOrWhiteSpace(searchString))
            {
                _brancheslist = _brancheslist.Where(c => c.BranchName
                    .ToLower().Contains(searchString.ToLower()) || c.BranchCode.ToString().Contains(searchString.ToLower())).ToList();
            }

            searchRecordCount = _brancheslist.Count;

            IOrderedEnumerable<Branch> sortedClients = null;
            foreach (var sortedColumn in sortedColumns)
            {
                switch (sortedColumn.PropertyName)
                {
                    case "CreatedDate":
                        sortedClients = sortedClients == null ? _brancheslist.CustomSort(sortedColumn.Direction, cust => cust.CreatedDate)
                            : sortedClients.CustomSort(sortedColumn.Direction, cust => cust.CreatedDate);
                        break;

                    case "BranchName":
                        sortedClients = sortedClients == null ? _brancheslist.CustomSort(sortedColumn.Direction, cust => cust.BranchName)
                            : sortedClients.CustomSort(sortedColumn.Direction, cust => cust.BranchName);
                        break;

                    case "Location":
                        sortedClients = sortedClients == null ? _brancheslist.CustomSort(sortedColumn.Direction, cust => cust.Location)
                            : sortedClients.CustomSort(sortedColumn.Direction, cust => cust.Location);
                        break;

                    case "TypeDesc":
                        sortedClients = sortedClients == null ? _brancheslist.CustomSort(sortedColumn.Direction, cust => cust.TypeDesc)
                            : sortedClients.CustomSort(sortedColumn.Direction, cust => cust.TypeDesc);
                        break;

                    case "C2BNumber":
                        sortedClients = sortedClients == null ? _brancheslist.CustomSort(sortedColumn.Direction, cust => cust.C2BNumber)
                            : sortedClients.CustomSort(sortedColumn.Direction, cust => cust.C2BNumber);
                        break;

                    case "BranchCode":
                        sortedClients = sortedClients == null ? _brancheslist.CustomSort(sortedColumn.Direction, cust => cust.BranchCode)
                            : sortedClients.CustomSort(sortedColumn.Direction, cust => cust.BranchCode);
                        break;

                    case "IsEnabled":
                        sortedClients = sortedClients == null ? _brancheslist.CustomSort(sortedColumn.Direction, cust => cust.IsEnabled)
                            : sortedClients.CustomSort(sortedColumn.Direction, cust => cust.IsEnabled);
                        break;                    
                }
            }

            return sortedClients.Skip(startIndex).Take(pageSize).ToList();
        }    
    
        [HttpGet]
        public ActionResult AddNewBranch()
        {
            ViewBag.BranchType = BranchType(null);
            return View();
        }

        [HttpPost]        
        public ActionResult AddNewBranch(Branch branch)
        {
            ViewBag.BranchType = BranchType(null);

            if (ModelState.IsValid)
            {
                try
                {
                    var findbranchbybranchcode = branchservice.GetAllBranches().Where(x => x.BranchCode == branch.BranchCode);
                    if (findbranchbybranchcode.Count() >= 1)
                    {
                        ModelState.AddModelError(string.Empty, string.Format("A branch with code {0} already exist.", branch.BranchCode));
                        return View(branch);
                    }
                    if (branch.BranchCode.Length != 3)
                    {
                        ModelState.AddModelError(string.Empty, "Branch code must be 3 characters long.");
                        return View(branch);    
                    }
                    branchservice.AddNewBranch(branch, serviceHeader);
                }
                catch(Exception ex)
                {
                    LoggerFactory.CreateLog().LogInfo("Error -> {0}", ex.Message + ex.InnerException + ex.StackTrace);
                    return View(branch);
                }
                return RedirectToAction("Index");
            }
            return View(branch);
        }

        [HttpGet]
        public ActionResult UpdateBranch(Guid Id)
        {
            var findbranchbyid = branchservice.FindBranchById(Id);
            if (findbranchbyid == null)
            {
                ModelState.AddModelError(string.Empty, "Could not find the branch.");
            }
            ViewBag.BranchType = BranchType(findbranchbyid);

            if (Id == null)
                throw new ArgumentNullException("Id cannot be null");

            return View(findbranchbyid);
        }

        [HttpPost]
        [ActionName("UpdateBranch")]        
        public ActionResult UpdateBranch(Branch branch)
        {
            var findbranchbyid = branchservice.FindBranchById(branch.Id);
            if (findbranchbyid == null)
            {
                ModelState.AddModelError(string.Empty, "Could not find the branch.");
            }
            ViewBag.BranchType = BranchType(findbranchbyid);

            if (ModelState.IsValid)
            {
                try
                {
                    if (branch.BranchCode.Length != 3)
                    {
                        ModelState.AddModelError(string.Empty, "Branch code must be 3 characters long.");
                        return View(branch);
                    }
                    
                    var findbranchbybranchcode = branchservice.GetAllBranches().Where(x => x.BranchCode == branch.BranchCode).Count();
                    if (findbranchbybranchcode > 1)
                    {
                        ModelState.AddModelError(string.Empty, string.Format("A branch with code {0} already exist", branch.BranchCode));
                        return View(branch);
                    }
                    findbranchbyid.BranchCode = branch.BranchCode;
                    findbranchbyid.Location = branch.Location;
                    findbranchbyid.C2BNumber = branch.C2BNumber;
                    findbranchbyid.BranchName = branch.BranchName;
                    findbranchbyid.IsEnabled = branch.IsEnabled;
                    branchservice.Update(branch, serviceHeader);
                    return RedirectToAction("Index");
                }

                catch(Exception ex)
                {
                    LoggerFactory.CreateLog().LogInfo("Error -> {0}", ex.Message + ex.InnerException + ex.StackTrace);
                    return View(branch);
                }                
            }
            return View(branch);
        }
    }
}

Nikopeshe.WebApplication/Views/Branch/AddNewBranch.cshtml
@model Nikopeshe.Entity.DataModels.Branch         
@using Nikopeshe.WebApplication.Extensions
@using Nikopeshe.WebApplication.Models
@{
    ViewBag.Title = "Create Branch";

    var accountselectlist = ViewBag.GLAccountSelectList as List<SelectListItem>;  
    
    var branchType = ViewBag.BranchType as List<CheckBoxListInfo>;
}

<script type="text/javascript">
    $(function () {
        $('input.unique').click(function () {
            $('#Type').attr('value', '');            
            $('input.unique:checked').not(this).removeAttr('checked');
        });
    });
</script>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(false, "Operation was unsuccessful. Please correct the errors and try again.")
    <fieldset>
        <legend>New Branch Details</legend>
        <div class="form-group">
            <div class="editor-label">
                @Html.LabelFor(model => model.BranchName)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.BranchName)
                @Html.ValidationMessageFor(model => model.BranchName)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.BranchCode)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.BranchCode)
                @Html.ValidationMessageFor(model => model.BranchCode)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Type)
            </div>
            <div class="editor-field">
                @Html.Raw(Html.CheckBoxList("Type", branchType, new { @class = "unique" }))
                @Html.ValidationMessageFor(model => model.Type)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.C2BNumber)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.C2BNumber)
                @Html.ValidationMessageFor(model => model.C2BNumber)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Location)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Location)
                @Html.ValidationMessageFor(model => model.Location)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.IsEnabled)
            </div>
            <div class="editor-field">
                @Html.CheckBoxFor(model => model.IsEnabled)
                @Html.ValidationMessageFor(model => model.IsEnabled)
            </div>

            <div class="editor-field"><input type="submit" value="Save" class="btn btn-default" /></div>
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Nikopeshe.WebApplication/Views/Branch/Index.cshtml
@using Nikopeshe.Entity.DataModels
@using Nikopeshe.WebApplication.Controllers
@using Microsoft.Web.Mvc
@{
    ViewBag.Title = "Branch List";

    var header = ViewBag.Header as string;
}

<h2>
    @Html.Raw(header)
</h2>
<script src="~/scripts/datatables/jquery.datatables.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#branchlistgrid').dataTable({
            // Ajax settings
            "sPaginationType": "full_numbers",
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "@(Url.Action("GetAllBranches", "Branch"))",
            "sServerMethod": "POST",
            // Callback settings
            "fnRowCallback": function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                /* row manipulation */
                var createdDate = new Date(parseInt(aData.CreatedDate.replace("/Date(", "").replace(")/", ""), 10));

                var h = ("0" + createdDate.getHours()).slice(-2);
                var m = ("0" + createdDate.getMinutes()).slice(-2);
                var s = ("0" + createdDate.getSeconds()).slice(-2);

                var dt_Created = $.datepicker.formatDate('dd/mm/yy', createdDate) + " " + h + ":" + m + ":" + s;

                $('td:eq(0)', nRow).html(dt_Created);

                $('td:eq(7)', nRow).html('<a href="/Branch/UpdateBranch/' + aData.Id + '">' + "Update Branch" + '</a>');

                return nRow;
            },
            // Display settings
            "iDisplayLength": 10,
            "bJQueryUI": true,
            "aaSorting": [[0, "desc"]],
            "aoColumns": [
            { "mDataProp": "CreatedDate", "sTitle": "Created Date" },
            { "mDataProp": "BranchName", "sTitle": "Branch Name" },
            { "mDataProp": "BranchCode", "sTitle": "Branch Code", "sWidth": "12%" },
            { "mDataProp": "Location", "sTitle": "Location", "sWidth": "12%" },
            { "mDataProp": "TypeDesc", "sTitle": "Type", "sWidth": "12%" },
            { "mDataProp": "C2BNumber", "sTitle": "Paybill Number", "sWidth": "12%" },
            { "mDataProp": "IsEnabled", "sTitle": "Is Opened?", "sWidth": "12%" },
            { "mDataProp": "Commands", "sTitle": "", "bSortable": false }]
        });
    });

</script>
<div>
    <fieldset>
        <legend>Branch List</legend>
        <div><p><p> @Html.ActionLink("Create New Branch", "AddNewBranch", "Branch", null, new { @class = "classname" })</p></div>
        <table cellpadding="0" cellspacing="1" id="branchlistgrid">
            <tbody>
                <tr>
                    <td colspan="7" class="dataTables_empty">
                        Loading data from server
                    </td>
                </tr>
            </tbody>
        </table>
    </fieldset>
</div>

<style>
    a.classname {
        background-color: #d3dce0;
        border: 1px solid #787878;
        text-decoration: none;
        cursor: pointer;
        font-size: 1.1em;
        border-radius: 3px;
        font-weight: 600;
        padding: 7px;
        margin-right: 8px;
        width: auto;
    }

        a.classname:hover {
            background-color: #E2E4FF;
        }
</style>

Nikopeshe.WebApplication/Views/Branch/UpdateBranch.cshtml
@model Nikopeshe.Entity.DataModels.Branch
@using Nikopeshe.WebApplication.Extensions
@using Nikopeshe.WebApplication.Models
@{
    ViewBag.Title = "Update Branch";

    var accountselectlist = ViewBag.GLAccountSelectList as List<SelectListItem>;
    var branchType = ViewBag.BranchType as List<CheckBoxListInfo>;
    
}

<script type="text/javascript">
    $(function () {
        $('input.unique').click(function () {
            $('#Type').attr('value', '');
            $('input.unique:checked').not(this).removeAttr('checked');
        });
    });
</script>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(false, "Operation was unsuccessful. Please correct the errors and try again.")
    <fieldset>
        <legend>New Branch Details</legend>
        <div class="form-group">
            <div class="editor-label">
                @Html.LabelFor(model => model.BranchName)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.BranchName)
                @Html.ValidationMessageFor(model => model.BranchName)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.BranchCode)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.BranchCode)
                @Html.ValidationMessageFor(model => model.BranchCode)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Type)
            </div>
            <div class="editor-field">
                @Html.Raw(Html.CheckBoxList("Type", branchType, new { @class = "unique" }))
                @Html.ValidationMessageFor(model => model.Type)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.C2BNumber)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.C2BNumber)
                @Html.ValidationMessageFor(model => model.C2BNumber)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Location)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Location)
                @Html.ValidationMessageFor(model => model.Location)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.IsEnabled)
            </div>
            <div class="editor-field">
                @Html.CheckBoxFor(model => model.IsEnabled)
                @Html.ValidationMessageFor(model => model.IsEnabled)
            </div>

            <div class="editor-field"><input type="submit" value="Update" class="btn btn-default" /></div>
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>