Nikopeshe.WebApplication/Controllers/SavingsProductController.cs
using Crosscutting.NetFramework.Logging;
using Nikopeshe.Data;
using Nikopeshe.Entity.DataModels;
using Nikopeshe.Infrastructure;
using Nikopeshe.Infrastructure.Datatables;
using Nikopeshe.Services.Interfaces;
using Nikopeshe.WebApplication.Attributes;
using Nikopeshe.WebApplication.Extensions;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data;
using System.Linq;
using System.ServiceModel;
using System.Web.Mvc;

namespace Nikopeshe.WebApplication.Controllers
{
    [Authorize(Roles = "Administrator")]
    [ExcludeFilter(typeof(AuthorizeIPAddressAttribute))]
    public class SavingsProductController : Controller
    {
        private readonly ISavingsProductService savingsproductservice;
        private readonly IChartofAccountService chartofaccountservice;
        ServiceHeader serviceHeader = CustomHeaderUtility.ReadHeader(OperationContext.Current);
        public SavingsProductController(ISavingsProductService _savingsproductservice, IChartofAccountService _chartofaccountservice)
        {
            if(_savingsproductservice == null || _chartofaccountservice == null)
                throw new ArgumentNullException("null service reference");

            this.savingsproductservice = _savingsproductservice;
            this.chartofaccountservice = _chartofaccountservice;
        }

        // GET: SavingsProduct
        public ActionResult Index()
        {            
            return View();
        }

        public JsonResult GetAllSavingsProduct(JQueryDataTablesModel datatablemodel)
        {
            var totalrecordcount = 0;

            var searchedrecordcount = 0;

            var pagecollection = savingsproductservice.GetAllSavingsAccountProducts(IsolationLevel.ReadUncommitted);

            var loanrequestList = GetAllSavingsProductList(startIndex: datatablemodel.iDisplayStart,
                pageSize: datatablemodel.iDisplayLength, sortedColumns: datatablemodel.GetSortedColumns(),
                totalRecordCount: out totalrecordcount, searchRecordCount: out searchedrecordcount, searchString: datatablemodel.sSearch, SavingsProductList: pagecollection);


            return Json(new JQueryDataTablesResponse<SavingsProduct>(items: loanrequestList,
                totalRecords: totalrecordcount,
                totalDisplayRecords: searchedrecordcount,
                sEcho: datatablemodel.sEcho));
        }

        public static IList<SavingsProduct> GetAllSavingsProductList(int startIndex, int pageSize, ReadOnlyCollection<SortedColumn> sortedColumns, out int totalRecordCount, out int searchRecordCount, string searchString, IList<SavingsProduct> SavingsProductList)
        {
            var GetSavingsProductList = SavingsProductList;

            totalRecordCount = GetSavingsProductList.Count;

            if (!string.IsNullOrWhiteSpace(searchString))
            {
                GetSavingsProductList = SavingsProductList.Where(c => c.ProductName
                    .ToLower().Contains(searchString.ToLower())).ToList();
            }

            searchRecordCount = GetSavingsProductList.Count;

            IOrderedEnumerable<SavingsProduct> sortedClients = null;
            foreach (var sortedColumn in sortedColumns)
            {
                switch (sortedColumn.PropertyName)
                {
                    case "CreatedDate":
                        sortedClients = sortedClients == null ? GetSavingsProductList.CustomSort(sortedColumn.Direction, cust => cust.CreatedDate)
                            : sortedClients.CustomSort(sortedColumn.Direction, cust => cust.CreatedDate);
                        break;

                    case "ChartofAccount.AccountName":
                        sortedClients = sortedClients == null ? GetSavingsProductList.CustomSort(sortedColumn.Direction, cust => cust.ChartofAccount.AccountName)
                            : sortedClients.CustomSort(sortedColumn.Direction, cust => cust.ChartofAccount.AccountName);
                        break;

                    case "ProductName":
                        sortedClients = sortedClients == null ? GetSavingsProductList.CustomSort(sortedColumn.Direction, cust => cust.ProductName)
                            : sortedClients.CustomSort(sortedColumn.Direction, cust => cust.ProductName);
                        break;

                    case "ProductCode":
                        sortedClients = sortedClients == null ? GetSavingsProductList.CustomSort(sortedColumn.Direction, cust => cust.ProductCode)
                            : sortedClients.CustomSort(sortedColumn.Direction, cust => cust.ProductCode);
                        break;

                    case "IsDefault":
                        sortedClients = sortedClients == null ? GetSavingsProductList.CustomSort(sortedColumn.Direction, cust => cust.IsDefault)
                            : sortedClients.CustomSort(sortedColumn.Direction, cust => cust.IsDefault);
                        break;

                    case "IsEnabled":
                        sortedClients = sortedClients == null ? GetSavingsProductList.CustomSort(sortedColumn.Direction, cust => cust.IsEnabled)
                            : sortedClients.CustomSort(sortedColumn.Direction, cust => cust.IsEnabled);
                        break;
                }
            }

            return sortedClients.Skip(startIndex).Take(pageSize).ToList();
        }

        [HttpGet]
        public ActionResult CreateNewSavingsProduct()
        {
            ViewBag.LiabilityChartofAccounts = GetLiabilityAccountTypes(Guid.Empty.ToString());

            return View();
        }

        [HttpPost]        
        public ActionResult CreateNewSavingsProduct(SavingsProduct savingproduct)
        {
            ViewBag.LiabilityChartofAccounts = GetLiabilityAccountTypes(Guid.Empty.ToString());

            try
            {                 
                if(ModelState.IsValid)
                {
                    string nextproductcode = savingsproductservice.NextSavingProductCode();
                    savingproduct.ProductCode = nextproductcode;
                    if (savingproduct.ChartofAccountId == Guid.Empty)
                    {
                        ModelState.AddModelError(string.Empty, "Chart of Chart Account cannot be null.");
                        return View(savingproduct);
                    }
                    if (savingproduct.IsDefault == true)
                    {
                        var defaultsavingsproductcount = savingsproductservice.DefaultSavingsProductCount();
                        if (defaultsavingsproductcount.Count() <= 0)
                        {
                            savingsproductservice.AddNewSavingsProduct(savingproduct, serviceHeader);
                            return RedirectToAction("Index");
                        }

                        else
                        {
                            ModelState.AddModelError(string.Empty, "Sorry, there is already a default savings product.");
                            return View(savingproduct);
                        }
                    }
                    else
                    {
                        savingsproductservice.AddNewSavingsProduct(savingproduct, serviceHeader);
                        return RedirectToAction("Index");
                    }    
                }
                return View(savingproduct);
            }                         
            
            catch(Exception ex)
            {
                LoggerFactory.CreateLog().LogInfo("Error -> {0}", ex.Message + ex.InnerException + ex.StackTrace);
                return View(savingproduct);
            }            
        }

        public ActionResult SavingProductDetails(Guid Id)
        {
            var findsavingproductbyid = savingsproductservice.FindSavingsProductById(Id);

            ViewBag.SavingsProductname = findsavingproductbyid.ProductName;

            return View(findsavingproductbyid);
        }

        [HttpGet]
        public ActionResult EditSavingProduct(Guid Id)
        {
            var findsavingsproductbyid = savingsproductservice.FindSavingsProductById(Id);

            ViewBag.LiabilityChartofAccounts = GetLiabilityAccountTypes(Guid.Empty.ToString());

            return View(findsavingsproductbyid);
        }
        
        [HttpPost]
        public ActionResult EditSavingProduct(SavingsProduct savingproduct)
        {
            ViewBag.LiabilityChartofAccounts = GetLiabilityAccountTypes(Guid.Empty.ToString());

            if (ModelState.IsValid)
            {
                try
                {
                    if (savingproduct.ChartofAccountId == Guid.Empty)
                    {
                        ModelState.AddModelError(string.Empty, "Chart of Chart Account cannot be null.");
                        return View(savingproduct);
                    }
                    var defaultsavingsproductcount = savingsproductservice.DefaultSavingsProductCount();
                    var findsavingsproductbyid = savingsproductservice.FindSavingsProductById(savingproduct.Id);
                    if (savingproduct.IsDefault == true)
                    {                        
                        if(defaultsavingsproductcount.Count() == 0)
                        {
                            findsavingsproductbyid.ChartofAccountId = savingproduct.ChartofAccountId;
                            findsavingsproductbyid.ProductName = savingproduct.ProductName;
                            findsavingsproductbyid.IsEnabled = savingproduct.IsEnabled;
                            findsavingsproductbyid.IsDefault = savingproduct.IsDefault;

Nikopeshe.WebApplication/Views/Products/AddNewLoanProduct.cshtml
@model Nikopeshe.Entity.DataModels.LoanProduct
@using Nikopeshe.WebApplication.Models
@using Nikopeshe.WebApplication.Extensions

@{
    ViewBag.Title = "New Loan Product";

    var accountselectlist = ViewBag.GLAccountSelectList as List<SelectListItem>;
    var interestChargeType = ViewBag.InterestChargeTypeCheckList as List<CheckBoxListInfo>;
    var incomeGL = ViewBag.IncomeGLAccount as List<SelectListItem>;
    var chargeinfo = ViewBag.CheckBoxList as List<CheckBoxListInfo>;
}

<script type="text/javascript">
    $(function () {
        $('input.unique').click(function () {
            $('input.unique:checked').not(this).removeAttr('checked');
        });
    });
</script>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(false, "Operation was unsuccessful. Please correct the errors and try again.")
    <fieldset>
        <legend>Loan Product Details</legend>
        <div class="form-group">
            <div class="editor-label">
                @Html.LabelFor(model => model.ProductName)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.ProductName)
                @Html.ValidationMessageFor(model => model.ProductName)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.InterestChargeType)
            </div>
            <div class="editor-field">
                @Html.Raw(Html.CheckBoxList("InterestChargeType", interestChargeType, new { @class = "unique" }))
                @Html.ValidationMessageFor(model => model.InterestChargeType)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.InterestValue)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.InterestValue)
                @Html.ValidationMessageFor(model => model.InterestValue)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Term)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Term)
                @Html.ValidationMessageFor(model => model.Term)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.MinimumAmount)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.MinimumAmount)
                @Html.ValidationMessageFor(model => model.MinimumAmount)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.MaximumAmount)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.MaximumAmount)
                @Html.ValidationMessageFor(model => model.MaximumAmount)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.DefaultLoanAmount)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.DefaultLoanAmount)
                @Html.ValidationMessageFor(model => model.DefaultLoanAmount)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.LoanGLAccountId, "Loan GL Account")
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(model => model.LoanGLAccountId, accountselectlist)
                @Html.ValidationMessageFor(model => model.LoanGLAccountId)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.InterestGLAccountId, "Interest Account GL")
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(model => model.InterestGLAccountId, incomeGL)
                @Html.ValidationMessageFor(model => model.InterestGLAccountId)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.PaymentFrequencyType)
            </div>
            <div class="editor-field">
                @Html.EnumDropDownListFor(model => model.PaymentFrequencyType, "Payment Frequency")
                @Html.ValidationMessageFor(model => model.PaymentFrequencyType)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.PrincipalRecoveryMethod)
            </div>
            <div class="editor-field">
                @Html.EnumDropDownListFor(model => model.PrincipalRecoveryMethod, "Pricipal Recovery Method")
                @Html.ValidationMessageFor(model => model.PrincipalRecoveryMethod)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.IsEnabled)
            </div>
            <div class="editor-field">
                @Html.CheckBoxFor(model => model.IsEnabled)
                @Html.ValidationMessageFor(model => model.IsEnabled)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.IsMicroLoan)
            </div>
            <div class="editor-field">
                @Html.CheckBoxFor(model => model.IsMicroLoan)
                @Html.ValidationMessageFor(model => model.IsMicroLoan)
            </div>

            @if (chargeinfo.Count != 0)
            {
                <div class="editor-label">
                    <b>@Html.LabelFor(model => model.Charges)</b>
                </div>
                <div class="editor-field">
                    @Html.Raw(Html.CheckBoxList("Charge", chargeinfo))
                </div>
            }

            <div class="editor-field"><input type="submit" value="Save" class="btn btn-default" /></div>
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Nikopeshe.WebApplication/Views/Products/EditSavingProduct.cshtml
@model Nikopeshe.Entity.DataModels.SavingsProduct

@{
    ViewBag.Title = "New Savings Product";

    var liabilitychartofaccount = ViewBag.LiabilityChartofAccounts as IList<SelectListItem>;
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>Savings Product Details</legend>
        @Html.ValidationSummary(false, "Operation was unsuccessful. Please correct the errors and try again.")
        <div class="form-group">
            <div class="editor-label">
                @Html.LabelFor(model => model.ChartofAccountId, "Savings GL Account")
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(model => model.ChartofAccountId, liabilitychartofaccount)
                @Html.ValidationMessageFor(model => model.ChartofAccountId)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.ProductName)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.ProductName)
                @Html.ValidationMessageFor(model => model.ProductName)
            </div>           

            <div class="editor-label">
                @Html.LabelFor(model => model.IsDefault)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.IsDefault)
                @Html.ValidationMessageFor(model => model.IsDefault)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.IsEnabled)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.IsEnabled)
                @Html.ValidationMessageFor(model => model.IsEnabled)
            </div>

            <div class="editor-field"><input type="submit" value="Save" class="btn btn-default" /></div>
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "SavingsProduct")
</div>


Nikopeshe.WebApplication/Views/Products/Index.cshtml
@{
    ViewBag.Title = "Products";
}
<fieldset>
    <legend>Products</legend>
    <ol>
        <li> @Html.ActionLink("Loan Products", "LoanProducts", "Products")</li>
        <li> @Html.ActionLink("Savings Products", "SavingsProduct", "Products")</li>       
    </ol>
</fieldset>

Nikopeshe.WebApplication/Views/Products/LoanProductCharges.cshtml
@using Nikopeshe.Entity.DataModels
@using Nikopeshe.WebApplication.Controllers
@using Microsoft.Web.Mvc
@{
    ViewBag.Title = "Loan Products Charges";

    var header = ViewBag.Header as string;
    var productname = ViewBag.LoanProductName as string;
    var Id = ViewBag.Id;
        
}

<h2>
    @Html.Raw(header)
</h2>
<script src="~/scripts/datatables/jquery.datatables.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#loanproductschargesgrid').dataTable({
            // Ajax settings
            "sPaginationType": "full_numbers",
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "@(Url.Action("GetAllLoanProductCharges", "Products", new { id = Id }))",
            "sServerMethod": "POST",
            // Callback settings
            "fnRowCallback": function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                /* row manipulation */
                var createdDate = new Date(parseInt(aData.CreatedDate.replace("/Date(", "").replace(")/", ""), 10));

                var h = ("0" + createdDate.getHours()).slice(-2);
                var m = ("0" + createdDate.getMinutes()).slice(-2);
                var s = ("0" + createdDate.getSeconds()).slice(-2);

                var dt_Created = $.datepicker.formatDate('dd/mm/yy', createdDate) + " " + h + ":" + m + ":" + s;

                $('td:eq(0)', nRow).html(dt_Created);
                $('td:eq(5)', nRow).html('<a href="/Loanproduct/editproduct/' + aData.Id + '">' +
                "Edit" + '</a>');
                return nRow;
            },
            // Display settings
            "iDisplayLength": 10,
            "bJQueryUI": true,
            "aaSorting": [[0, "desc"]],
            "aoColumns": [
            { "mDataProp": "CreatedDate", "sTitle": "Created Date" },
            { "mDataProp": "LoanProduct.ProductName", "sTitle": "Product Name" },
            { "mDataProp": "Charges.ChargeName", "sTitle": "Charge Name" },
            { "mDataProp": "Charges.ChargeRecoveryMethodDesc", "sTitle": "Charge RecoveryMethod Desc" },
            { "mDataProp": "Charges.IsRecurring", "sTitle": "Is Charge Recurring" }]
        });
    });

</script>
<div>
    <fieldset>
        <legend>Loan Charges for @productname</legend>        
        <table cellpadding="0" cellspacing="1" id="loanproductschargesgrid">
            <tbody>
                <tr>
                    <td colspan="7" class="dataTables_empty">
                        Loading data from server
                    </td>
                </tr>
            </tbody>
        </table>
    </fieldset>
</div>
@Html.ActionLink("Back List", "loanproducts")


Nikopeshe.WebApplication/Views/Products/LoanProducts.cshtml
@using Nikopeshe.Entity.DataModels
@using Nikopeshe.WebApplication.Controllers
@using Microsoft.Web.Mvc
@{
    ViewBag.Title = "Loan Products";

    var header = ViewBag.Header as string;
}

<h2>
    @Html.Raw(header)
</h2>
<script src="~/scripts/datatables/jquery.datatables.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#allloanproductsgrid').dataTable({
            // Ajax settings
            "sPaginationType": "full_numbers",
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "@(Url.Action("getallloanproducservice", "Products"))",
            "sServerMethod": "POST",
            // Callback settings
            "fnRowCallback": function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                /* row manipulation */
                var createdDate = new Date(parseInt(aData.CreatedDate.replace("/Date(", "").replace(")/", ""), 10));

                var h = ("0" + createdDate.getHours()).slice(-2);
                var m = ("0" + createdDate.getMinutes()).slice(-2);
                var s = ("0" + createdDate.getSeconds()).slice(-2);

                var dt_Created = $.datepicker.formatDate('dd/mm/yy', createdDate) + " " + h + ":" + m + ":" + s;

                $('td:eq(0)', nRow).html(dt_Created);

                var value = aData.MaximumAmount;
                var num = value.toFixed(2).replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1,");
                $('td:eq(6)', nRow).html(num);

                var value1 = aData.MinimumAmount;
                var num1 = value1.toFixed(2).replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1,");
                $('td:eq(7)', nRow).html(num1);

                var value2 = aData.DefaultLoanAmount;
                var num2 = value2.toFixed(2).replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1,");
                $('td:eq(8)', nRow).html(num2);

                $('td:eq(12)', nRow).html('<a href="/products/editproduct/' + aData.Id + '">' +
                "Edit" + '</a>' + '</a>' + ' | ' + '<a href="/products/LoanProductCharges/' + aData.Id + '">' +
                    "Applied Charges" + '</a>');
                return nRow;
            },
            // Display settings
            "iDisplayLength": 10,
            "bJQueryUI": true,
            "aaSorting": [[0, "desc"]],
            "aoColumns": [
            { "mDataProp": "CreatedDate", "sTitle": "Created Date", "sWidth": "12%" },
            { "mDataProp": "ProductName", "sTitle": "Product Name" },
            { "mDataProp": "InterestChargeTypeDesc", "sTitle": "Interest Charge Type" },
            { "mDataProp": "InterestValue", "sTitle": "Interest Value", "sWidth": "8%" },
            { "mDataProp": "ProductCode", "sTitle": "Product Code", "sWidth": "8%" },
            { "mDataProp": "Term", "sTitle": "Term" },
            { "mDataProp": "MaximumAmount", "sTitle": "Max Amount", "sWidth": "10%" },
            { "mDataProp": "MinimumAmount", "sTitle": "Min Amount", "sWidth": "10%" },
            { "mDataProp": "DefaultLoanAmount", "sTitle": "Default Amount", "sWidth": "10%" },
            { "mDataProp": "IsEnabled", "sTitle": "Enabled" },
            { "mDataProp": "IsDefault", "sTitle": "Is Default" },
            { "mDataProp": "IsMicroLoan", "sTitle": "Is MicroLoan?" },
            { "mDataProp": "Commands", "sTitle": "", "bSortable": false }]
        });
    });

</script>
<div>
    <fieldset>
        <legend>Loan Product List</legend>
        <p>
            @if (Roles.IsUserInRole("Administrator"))
            {
                @Html.ActionLink("Add New Loan Product", "AddNewLoanProduct", "Products")
            }
        </p>
        <table cellpadding="0" cellspacing="1" id="allloanproductsgrid">
            <tbody>
                <tr>
                    <td colspan="7" class="dataTables_empty">
                        Loading data from server
                    </td>
                </tr>
            </tbody>
        </table>
    </fieldset>
</div>


Nikopeshe.WebApplication/Views/Products/SavingProductDetails.cshtml
@model Nikopeshe.Entity.DataModels.SavingsProduct

@{
    ViewBag.Title = "Loan Product Details";

    var productname = ViewBag.SavingsProductname as string;
}

<div>
    <fieldset>
        <legend>Details for @productname</legend>

        <div class="display-label">
            <b>@Html.DisplayNameFor(model => model.ProductName)</b>
        </div>

        <div class="display-field">
            @Html.DisplayFor(model => model.ProductName)
        </div>

        <div class="display-label">
            <b>@Html.DisplayNameFor(model => model.ProductCode)</b>
        </div>

        <div class="display-field">
            @Html.DisplayFor(model => model.ProductCode)
        </div>

        <div class="display-label">
            <b>@Html.DisplayNameFor(model => model.IsDefault)</b>
        </div>

        <div class="display-field">
            @Html.DisplayFor(model => model.IsDefault)
        </div>
        
        <div class="display-label">
            <b>@Html.DisplayNameFor(model => model.IsEnabled)</b>
        </div>

        <div class="display-field">
            @Html.DisplayFor(model => model.IsEnabled)
        </div>

        <div class="display-label">
            <b>@Html.DisplayNameFor(model => model.CreatedDate)</b>
        </div>

        <div class="display-field">
            @Html.DisplayFor(model => model.CreatedDate)
        </div>
    </fieldset>
</div>
<p>
    @Html.ActionLink("Edit", "editproduct", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "SavingsProduct")
</p>

Nikopeshe.WebApplication/Views/Products/createnewsavingsproduct.cshtml
@model Nikopeshe.Entity.DataModels.SavingsProduct

@{
    ViewBag.Title = "New Savings Product";
    
    var liabilitychartofaccount = ViewBag.LiabilityChartofAccounts as IList<SelectListItem>;
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>Savings Product Details</legend>
        @Html.ValidationSummary(false, "Operation was unsuccessful. Please correct the errors and try again.")
        <div class="form-group">
            <div class="editor-label">
                @Html.LabelFor(model => model.ChartofAccountId, "Saving GL Account")
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(model => model.ChartofAccountId, liabilitychartofaccount)
                @Html.ValidationMessageFor(model => model.ChartofAccountId)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.ProductName)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.ProductName)
                @Html.ValidationMessageFor(model => model.ProductName)
            </div>                                   
                       
            <div class="editor-label">
                @Html.LabelFor(model => model.IsDefault)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.IsDefault)
                @Html.ValidationMessageFor(model => model.IsDefault)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.IsEnabled)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.IsEnabled)
                @Html.ValidationMessageFor(model => model.IsEnabled)
            </div>

            <div class="editor-field"><input type="submit" value="Save" class="btn btn-default" /></div>
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "SavingsProduct")
</div>
