Nikopeshe.WebApplication_Backup_2016.08.02_01.18.59/Controllers/TransactionsHistoryController.cs
using Crosscutting.NetFramework.Logging;
using Nikopeshe.Data;
using Nikopeshe.Entity.DataModels;
using Nikopeshe.Infrastructure.Datatables;
using Nikopeshe.Services.Interfaces;
using Nikopeshe.WebApplication.Attributes;
using Nikopeshe.WebApplication.Extensions;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.ServiceModel;
using System.Web;
using System.Web.Mvc;

namespace Nikopeshe.WebApplication.Controllers
{
    [Authorize(Roles = "LoanOfficer, Administrator, LoanManager")]
    [ExcludeFilter(typeof(AuthorizeIPAddressAttribute))]
    public class TransactionsHistoryController : Controller
    {
        private readonly ITransactionHistoryService transactionhistoryservice;
        private readonly ICustomerService customerservice;
        ServiceHeader serviceHeader = CustomHeaderUtility.ReadHeader(OperationContext.Current);
        public TransactionsHistoryController(ITransactionHistoryService _transactionhistoryservice, ICustomerService _customerservice)
        {
            if(_transactionhistoryservice == null || _customerservice == null)
                throw new ArgumentNullException("null service reference");

            this.transactionhistoryservice = _transactionhistoryservice;
            this.customerservice = _customerservice;
        }

        //
        // GET: /TransactionsHistory/        
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult getalltransactionhistory(JQueryDataTablesModel datatablemodel)
        {            
            var pagecollection = transactionhistoryservice.GetAllLoanTransactionsHistory();

            int totalRecordCount = 0;

            int searchRecordCount = 0;

            var transactionhistoryList = GetAllTransactionsHistory(startIndex: datatablemodel.iDisplayStart,
                pageSize: datatablemodel.iDisplayLength, sortedColumns: datatablemodel.GetSortedColumns(),
                totalRecordCount: out totalRecordCount, searchRecordCount: out searchRecordCount, searchString: datatablemodel.sSearch, TransactionsHistoryList: pagecollection);


            return Json(new JQueryDataTablesResponse<TransactionHistory>(items: transactionhistoryList,
                totalRecords: totalRecordCount,
                totalDisplayRecords: searchRecordCount,
                sEcho: datatablemodel.sEcho));
        }

        public static IList<TransactionHistory> GetAllTransactionsHistory(int startIndex, int pageSize, ReadOnlyCollection<SortedColumn> sortedColumns, out int totalRecordCount, out int searchRecordCount, string searchString, IList<TransactionHistory> TransactionsHistoryList)
        {
            var GetTransactionsHistoryList = TransactionsHistoryList;

            totalRecordCount = GetTransactionsHistoryList.Count;

            if (!string.IsNullOrWhiteSpace(searchString))
            {
                GetTransactionsHistoryList = GetTransactionsHistoryList.Where(c => c.Customer.FullName
                    .ToLower().Contains(searchString.ToLower())).ToList();
            }

            searchRecordCount = GetTransactionsHistoryList.Count;

            IOrderedEnumerable<TransactionHistory> sortedClients = null;
            foreach (var sortedColumn in sortedColumns)
            {
                switch (sortedColumn.PropertyName)
                {
                    case "CreatedDate":
                        sortedClients = sortedClients == null ? GetTransactionsHistoryList.CustomSort(sortedColumn.Direction, cust => cust.CreatedDate)
                            : sortedClients.CustomSort(sortedColumn.Direction, cust => cust.CreatedDate);
                        break;

                    case "Customer.FullName":
                        sortedClients = sortedClients == null ? GetTransactionsHistoryList.CustomSort(sortedColumn.Direction, cust => cust.Customer.FullName)
                            : sortedClients.CustomSort(sortedColumn.Direction, cust => cust.Customer.FullName);
                        break;

                    case "Amount":
                        sortedClients = sortedClients == null ? GetTransactionsHistoryList.CustomSort(sortedColumn.Direction, cust => cust.Amount)
                            : sortedClients.CustomSort(sortedColumn.Direction, cust => cust.Amount);
                        break;

                    case "TransactionTypeDesc":
                        sortedClients = sortedClients == null ? GetTransactionsHistoryList.CustomSort(sortedColumn.Direction, cust => cust.TransactionTypeDesc)
                            : sortedClients.CustomSort(sortedColumn.Direction, cust => cust.TransactionTypeDesc);
                        break;

                    case "TransactionDateTime":
                        sortedClients = sortedClients == null ? GetTransactionsHistoryList.CustomSort(sortedColumn.Direction, cust => cust.TransactionDateTime)
                            : sortedClients.CustomSort(sortedColumn.Direction, cust => cust.TransactionDateTime);
                        break;

                    case "TypeDesc":
                        sortedClients = sortedClients == null ? GetTransactionsHistoryList.CustomSort(sortedColumn.Direction, cust => cust.TypeDesc)
                            : sortedClients.CustomSort(sortedColumn.Direction, cust => cust.TypeDesc);
                        break;                   
                }
            }

            return sortedClients.Skip(startIndex).Take(pageSize).ToList();
        }

        [HttpGet]
        public ActionResult addtransactionhistory()
        {
            ViewBag.Customerlist = GetCustomerlist(Guid.Empty.ToString());

            return View();
        }

        [HttpPost]        
        public ActionResult addtransactionhistory(TransactionHistory transactionhistory)
        {
            ViewBag.Customerlist = GetCustomerlist(Guid.Empty.ToString());            

            transactionhistory.TransactionDateTime = DateTime.Now;

            if(transactionhistory.CustomerId == Guid.Empty)
            {
                ModelState.AddModelError(string.Empty, "Please select a customer.");
                return View(transactionhistory);
            }

            if(string.Concat(transactionhistory.Type) == "0" || string.Concat(transactionhistory.TransactionType) == "0")
            {
                ModelState.AddModelError(string.Empty, "Transaction Type or Type cannot be null");
                return View(transactionhistory);
            }

            if(ModelState.IsValid)
            {
                try
                {                    
                    transactionhistoryservice.AddNewTransactionHistory(transactionhistory, serviceHeader);

                    return RedirectToAction("Index");
                }
                catch(Exception ex)
                {
                    LoggerFactory.CreateLog().LogInfo("Error -> {0}", ex.Message + ex.InnerException + ex.StackTrace);
                    return View(transactionhistory);
                }
            }
            return View(transactionhistory);
        }

        [HttpGet]
        public ActionResult customertransactionhistory(Guid Id)
        {            
            ViewBag.CustomerId = Id;

            return View();
        }

        public JsonResult Getcustomertransactionhistory(Guid id, JQueryDataTablesModel datatablemodel)
        {           
            var pagecollection = transactionhistoryservice.GetAllCustomerTransationHistoryByCustomerId(id);
            int totalRecordCount = 0;

            int searchRecordCount = 0;

            var transactionhistoryList = GetAllCustomerTransactionsHistory(startIndex: datatablemodel.iDisplayStart,
                pageSize: datatablemodel.iDisplayLength, sortedColumns: datatablemodel.GetSortedColumns(),
                totalRecordCount: out totalRecordCount, searchRecordCount: out searchRecordCount, searchString: datatablemodel.sSearch, TransactionsHistoryList: pagecollection);


            return Json(new JQueryDataTablesResponse<TransactionHistory>(items: transactionhistoryList,
                totalRecords: totalRecordCount,
                totalDisplayRecords: searchRecordCount,
                sEcho: datatablemodel.sEcho));
        }

        public static IList<TransactionHistory> GetAllCustomerTransactionsHistory(int startIndex, int pageSize, ReadOnlyCollection<SortedColumn> sortedColumns, out int totalRecordCount, out int searchRecordCount, string searchString, IList<TransactionHistory> TransactionsHistoryList)
        {
            var GetTransactionsHistoryList = TransactionsHistoryList;

            totalRecordCount = GetTransactionsHistoryList.Count;

            if (!string.IsNullOrWhiteSpace(searchString))
            {
                GetTransactionsHistoryList = GetTransactionsHistoryList.Where(c => c.Customer.FullName
                    .ToLower().Contains(searchString.ToLower())).ToList();
            }

            searchRecordCount = GetTransactionsHistoryList.Count;

            IOrderedEnumerable<TransactionHistory> sortedClients = null;
            foreach (var sortedColumn in sortedColumns)
            {
                switch (sortedColumn.PropertyName)
                {
                    case "CreatedDate":
                        sortedClients = sortedClients == null ? GetTransactionsHistoryList.CustomSort(sortedColumn.Direction, cust => cust.CreatedDate)
                            : sortedClients.CustomSort(sortedColumn.Direction, cust => cust.CreatedDate);
                        break;

                    case "Customer.FullName":

Nikopeshe.WebApplication_Backup_2016.08.02_01.18.59/Views/TransactionsHistory/Index.cshtml
@using Nikopeshe.Entity.DataModels
@using Nikopeshe.WebApplication.Controllers
@using Microsoft.Web.Mvc
@{
    ViewBag.Title = "Transactions";

    string header = ViewBag.Header as string;
}

<h2>
    @Html.Raw(header)
</h2>

<script type="text/javascript">
    $(document).ready(function () {

        $('#transactionhistory').dataTable({
            // Ajax settings
            "sPaginationType": "full_numbers",
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "@(Url.Action("getalltransactionhistory", "TransactionsHistory"))",
            "sServerMethod": "POST",
            // Callback settings
            "fnRowCallback": function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                /* row manipulation */

                var createdDate = new Date(parseInt(aData.CreatedDate.replace("/Date(", "").replace(")/", ""), 10));

                var h = ("0" + createdDate.getHours()).slice(-2);
                var m = ("0" + createdDate.getMinutes()).slice(-2);
                var s = ("0" + createdDate.getSeconds()).slice(-2);

                var dt_Created = $.datepicker.formatDate('dd/mm/yy', createdDate) + " " + h + ":" + m + ":" + s;

                $('td:eq(0)', nRow).html(dt_Created);

                var createdDate = new Date(parseInt(aData.TransactionDateTime.replace("/Date(", "").replace(")/", ""), 10));

                var h = ("4" + createdDate.getHours()).slice(-2);
                var m = ("4" + createdDate.getMinutes()).slice(-2);
                var s = ("4" + createdDate.getSeconds()).slice(-2);

                var dt_Created = $.datepicker.formatDate('dd/mm/yy', createdDate) + " " + h + ":" + m + ":" + s;

                $('td:eq(4)', nRow).html(dt_Created);

                //$('td:eq(6)', nRow).html('<a href="/Loanrequest/loanrequestdetails/' + aData.Id + '">' +
                //"Loan Details" + '</a>');
                return nRow;

            },
            // Display settings
            "iDisplayLength": 10,
            "bJQueryUI": true,
            "aaSorting": [[0, "desc"]],
            "aoColumns": [
            { "mDataProp": "CreatedDate", "sTitle": "Created Date" },
            { "mDataProp": "Customer.FullName", "sTitle": "Customer Name" },
            { "mDataProp": "Amount", "sTitle": "Amount", "sWidth": "12%" },
            { "mDataProp": "TransactionTypeDesc", "sTitle": "Transaction Type" },
            { "mDataProp": "TransactionDateTime", "sTitle": "Trx DateTime" },
            { "mDataProp": "TypeDesc", "sTitle": "Type" }],            
            //{ "mDataProp": "Commands", "sTitle": "" }],
        });
    });

</script>
<div>
    <fieldset>
        <legend>Transaction History</legend>
        <div>
            @if (Roles.IsUserInRole("Administrator"))
            {
                <p>@Html.ActionLink("New Transaction History", "addtransactionhistory", "TransactionsHistory")</p>
            }
        </div>
        <table cellpadding="0" cellspacing="1" id="transactionhistory">
            <tbody>
                <tr>
                    <td colspan="7" class="dataTables_empty">
                        Loading data from server
                    </td>
                </tr>
            </tbody>
        </table>
        
        <div></div>
    </fieldset>
</div>


Nikopeshe.WebApplication_Backup_2016.08.02_01.18.59/Views/TransactionsHistory/addtransactionhistory.cshtml
@model Nikopeshe.Entity.DataModels.TransactionHistory

@{
    ViewBag.Title = "Add Transaction Tistory";
    
    var customerlist = ViewBag.Customerlist as List<SelectListItem>;        
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <fieldset>
        <legend>Add Transaction History</legend>
        <div class="form-group">
            @Html.ValidationSummary(false)

            <div class="editor-label">
                @Html.LabelFor(model => model.CustomerId)
                <div class="editor-field">
                    @Html.DropDownListFor(model => model.CustomerId, customerlist)
                    @Html.ValidationMessageFor(model => model.CustomerId)
                </div>
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Amount)
                <div class="editor-field">
                    @Html.EditorFor(model => model.Amount)
                    @Html.ValidationMessageFor(model => model.Amount)
                </div>
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.TransactionType)
                <div class="editor-field">
                    @Html.EnumDropDownListFor(model => model.TransactionType, "Select...")
                    @Html.ValidationMessageFor(model => model.TransactionType)
                </div>
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Type)
                <div class="editor-field">
                    @Html.EnumDropDownListFor(model => model.Type, "Select...")
                    @Html.ValidationMessageFor(model => model.Type)
                </div>
            </div>

            <div class="editor-field"><input type="submit" value="Create" class="btn btn-default" /></div>
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Nikopeshe.WebApplication_Backup_2016.08.02_01.18.59/Views/TransactionsHistory/customertransactionhistory.cshtml
@using Nikopeshe.Entity.DataModels
@using Nikopeshe.WebApplication.Controllers
@using Microsoft.Web.Mvc
@{
    ViewBag.Title = "Transaction History";

    string header = ViewBag.Header as string;

    var customerid = ViewBag.CustomerId;
}

<h2>
    @Html.Raw(header)
</h2>

<script type="text/javascript">
    $(document).ready(function () {

        $('#transactionhistorygrid').dataTable({
            // Ajax settings
            "sPaginationType": "full_numbers",
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "@(Url.Action("Getcustomertransactionhistory", "TransactionsHistory", new { id = customerid }))",            
            "sServerMethod": "POST",
            // Callback settings
            "fnRowCallback": function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                /* row manipulation */

                var paymentdueDate = new Date(parseInt(aData.CreatedDate.replace("/Date(", "").replace(")/", ""), 10));
                $('td:eq(0)', nRow).html(paymentdueDate.getDate() + "/" + paymentdueDate.getMonth() + 1 + "/" + paymentdueDate.getFullYear());

                var transactiondate = new Date(parseInt(aData.TransactionDateTime.replace("/Date(", "").replace(")/", ""), 10));
                $('td:eq(4)', nRow).html(transactiondate.getMonth() + 1 + "/" + transactiondate.getDate() + "/" + transactiondate.getFullYear());


                //$('td:eq(6)', nRow).html('<a href="/Loanrequest/loanrequestdetails/' + aData.Id + '">' +
                //"Loan Details" + '</a>');
                return nRow;

            },
            // Display settings
            "iDisplayLength": 10,
            "bJQueryUI": true,
            "aaSorting": [[0, "desc"]],
            "aoColumns": [
            { "mDataProp": "CreatedDate", "sTitle": "Created Date" },
            { "mDataProp": "Customer.FullName", "sTitle": "Customer Name" },
            { "mDataProp": "Amount", "sTitle": "Amount", "sWidth": "12%" },
            { "mDataProp": "TransactionTypeDesc", "sTitle": "Transaction Type" },
            { "mDataProp": "TransactionDateTime", "sTitle": "Trx DateTime" },
            { "mDataProp": "TypeDesc", "sTitle": "Type" }],
            //{ "mDataProp": "Commands", "sTitle": "" }],
        });
    });

</script>
<div>
    <fieldset>
        <legend>Transaction History</legend>
        <table cellpadding="0" cellspacing="1" id="transactionhistorygrid">
            <tbody>
                <tr>
                    <td colspan="7" class="dataTables_empty">
                        Loading data from server
                    </td>
                </tr>
            </tbody>
        </table>
        <div></div>
    </fieldset>
</div>
