Nikopeshe.WebApplication_Backup_2016.08.02_01.18.59/Controllers/DocumentManagementController.cs
using Crosscutting.NetFramework.Logging;
using Nikopeshe.Data;
using Nikopeshe.Entity.DataModels;
using Nikopeshe.Infrastructure.Datatables;
using Nikopeshe.Services.InterfaceImplementations;
using Nikopeshe.Services.Interfaces;
using Nikopeshe.WebApplication.Attributes;
using Nikopeshe.WebApplication.Extensions;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.ServiceModel;
using System.Web;
using System.Web.Mvc;

namespace Nikopeshe.WebApplication.Controllers
{
    [Authorize]
    [ExcludeFilter(typeof(AuthorizeIPAddressAttribute))]
    public class DocumentManagementController : Controller
    {
        private readonly ICustomerDocumentService customerdocumentservice;
        private readonly ICustomerService customerservice;
        private readonly ILoanRequestService loanrequestservice;
        private readonly ILoanRequestDocumentsService loanrequestdocumentservice;
        ServiceHeader serviceHeader = CustomHeaderUtility.ReadHeader(OperationContext.Current);
        public DocumentManagementController(ICustomerDocumentService _customerdocumentservice, ILoanRequestService _loanrequestservice,ICustomerService _customerservice, ILoanRequestDocumentsService _loanrequestdocumentservice)
        {
            this.loanrequestdocumentservice = _loanrequestdocumentservice;
            this.loanrequestservice = _loanrequestservice;
            this.customerdocumentservice = _customerdocumentservice;
            this.customerservice = _customerservice;
        }
        // GET: DocumentManagement
      
        public FileResult View(Guid Id)
        {
            var document = customerdocumentservice.FindCustomerDocumentById(Id);

            return File(document.Image, "application/pdf");
        }

        public FileResult LoanRequestDocumentView(Guid Id)
        {
            var document = loanrequestdocumentservice.FindLoanRequestDocumentById(Id);

            return File(document.Image, "application/pdf");
        }

        public FileResult CustomerDocumentsView(Guid Id)
        {
            var document = customerdocumentservice.FindCustomerDocumentById(Id);

            return File(document.Image, "application/pdf");
        }

        public PartialViewResult PDFPartialView()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult UploadFile(Guid id)
        {
            if (id == Guid.Empty)
            {
                throw new ArgumentNullException("Id is required.");
            }

            ViewBag.Id = id;
            var findcustomer = customerservice.FindCustomerById(id);
            if (findcustomer == null)
            {
                ModelState.AddModelError(string.Empty, "Failed while retrieving customers information.");
                return View();
            }
            ViewBag.CustomerName = findcustomer.FullName;
            ViewBag.MobileNumber = findcustomer.MobileNumber;
            ViewBag.IdNumber = findcustomer.IDNumber;

            //var customerlist = CustomerSelectList(Guid.Empty.ToString());
            //ViewBag.CustomerSelectList = customerlist;
            return View();
        }

        /// <summary>
        /// Upload Customer Document
        /// </summary>
        /// <returns></returns>
        ///
        [HttpPost]        
        public ActionResult UploadFile(Guid id, CustomerDocument customerdocument, HttpPostedFileBase PostedFile)
        {
            if (id == Guid.Empty)
            {
                throw new ArgumentNullException("Id is required.");
            }

            ViewBag.Id = id;
            var findcustomer = customerservice.FindCustomerById(id);
            if (findcustomer == null)
            {
                ModelState.AddModelError(string.Empty, "Failed while retrieving customers information.");
                return View();
            }
            ViewBag.CustomerName = findcustomer.FullName;
            ViewBag.MobileNumber = findcustomer.MobileNumber;
            ViewBag.IdNumber = findcustomer.IDNumber;
            //var customerlist = CustomerSelectList(Guid.Empty.ToString());
            //ViewBag.CustomerSelectList = customerlist;                        

            //if (customerdocument.CustomerId == Guid.Empty)
            //{
            //    ModelState.AddModelError(string.Empty, "You must select a customer");
            //    return View(customerdocument);
            //}
            if (ModelState.IsValid)
            {
                try
                {                    
                    if(PostedFile != null && PostedFile.ContentLength > 0)
                    {
                        // extract only the fielname
                        var fileName = Path.GetFileName(PostedFile.FileName);
                        // store the file inside ~/App_Data/uploads folder
                        var path = Path.Combine(Server.MapPath("~/Content/Uploads"), fileName);
                        var getfileextension = Path.GetExtension(path);
                        if (getfileextension != ".pdf")
                        {
                            ModelState.AddModelError(string.Empty, "Wrong file type. The file must have .pdf extension");
                            return View(customerdocument);
                        }
                                                
                        PostedFile.SaveAs(path);
                        var fileData = new MemoryStream();
                        PostedFile.InputStream.CopyTo(fileData);
                        customerdocument.Image = fileData.ToArray();
                        customerdocument.CustomerId = findcustomer.Id;
                        customerdocument.Id = Guid.NewGuid();
                        customerdocumentservice.AddNewCustomerDocument(customerdocument, serviceHeader);
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "You must select a file.");
                        return View(customerdocument);
                    }                    
                }

                catch(Exception ex)
                {
                    LoggerFactory.CreateLog().LogInfo("Error -> {0}", ex.Message + ex.InnerException + ex.StackTrace);
                    return View(customerdocument);
                }
            }
            return View("UploadSuccess");
        }

        public ActionResult UploadSuccess()
        {
            return View();
        }

        public ActionResult CustomerDocuments(Guid Id)
        {
            ViewBag.Id = Id;
            var findcustomerr = customerservice.FindCustomerById(Id);
            ViewBag.CustomerId = findcustomerr.Id;
            ViewBag.CustomerName = findcustomerr.FullName;
            return View();
        }

        public JsonResult GetCustomerDocuments(JQueryDataTablesModel datatablemodel, Guid Id)
        {
            var customerdocuments = customerdocumentservice.GetAllCustomerDocuments(Id);

            int totalRecordCount = 0;

            int searchRecordCount = 0;

            var loanrequestList = GetAllCustomerDocument(startIndex: datatablemodel.iDisplayStart,
                pageSize: datatablemodel.iDisplayLength, sortedColumns: datatablemodel.GetSortedColumns(),
                totalRecordCount: out totalRecordCount, searchRecordCount: out searchRecordCount, searchString: datatablemodel.sSearch, CustomerDocumentList: customerdocuments);


            var results = Json(new JQueryDataTablesResponse<CustomerDocumentView>(items: loanrequestList,
                totalRecords: totalRecordCount,
                totalDisplayRecords: searchRecordCount,
                sEcho: datatablemodel.sEcho));

            results.MaxJsonLength = Int32.MaxValue;

            return results;
        }

        public static IList<CustomerDocumentView> GetAllCustomerDocument(int startIndex, int pageSize, ReadOnlyCollection<SortedColumn> sortedColumns, out int totalRecordCount, out int searchRecordCount, string searchString, IList<CustomerDocumentView> CustomerDocumentList)
        {
            var GetCustomerDocumentList = CustomerDocumentList;

            totalRecordCount = GetCustomerDocumentList.Count;

            if (!string.IsNullOrWhiteSpace(searchString))
            {
                GetCustomerDocumentList = CustomerDocumentList.Where(c => c.Customer.IDNumber
                    .ToLower().Contains(searchString.ToLower())
                    || c.Customer.MobileNumber.ToLower().Contains(searchString.ToLower())
                    ).ToList();            
            }

            searchRecordCount = GetCustomerDocumentList.Count;

            IOrderedEnumerable<CustomerDocumentView> sortedClients = null;
            foreach (var sortedColumn in sortedColumns)
            {
                switch (sortedColumn.PropertyName)
                {
                    case "CreatedDate":
                        sortedClients = sortedClients == null ? GetCustomerDocumentList.CustomSort(sortedColumn.Direction, cust => cust.CreatedDate)
                            : sortedClients.CustomSort(sortedColumn.Direction, cust => cust.CreatedDate);
                        break;

                    case "Customer.FullName":
                        sortedClients = sortedClients == null ? GetCustomerDocumentList.CustomSort(sortedColumn.Direction, cust => cust.Customer.FullName)
                            : sortedClients.CustomSort(sortedColumn.Direction, cust => cust.Customer.FullName);
                        break;

                    case "Customer.IDNumber":

Nikopeshe.WebApplication_Backup_2016.08.02_01.18.59/Views/DocumentManagement/CustomerDocuments.cshtml
@using Nikopeshe.Entity.DataModels
@using Nikopeshe.WebApplication.Controllers
@using Microsoft.Web.Mvc
@using Nikopeshe.WebApplication.Extensions
@{
    ViewBag.Title = "Loan Requests";

    string header = ViewBag.Header as string;

    var id = ViewBag.Id;

    var customername = ViewBag.CustomerName as string;

    var customerId = ViewBag.CustomerId;
}

<h2>
    @Html.Raw(header)
</h2>

<script type="text/javascript">
    $(document).ready(function () {

        $('#customerdocuments').dataTable({
            // Ajax settings
            "sPaginationType": "full_numbers",
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "@(Url.Action("GetCustomerDocuments", "DocumentManagement", new { id = id }))",
            "sServerMethod": "POST",
            // Callback settings
            "fnRowCallback": function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                /* row manipulation */

                var createdDate = new Date(parseInt(aData.CreatedDate.replace("/Date(", "").replace(")/", ""), 10));

                var h = ("0" + createdDate.getHours()).slice(-2);
                var m = ("0" + createdDate.getMinutes()).slice(-2);
                var s = ("0" + createdDate.getSeconds()).slice(-2);

                var dt_Created = $.datepicker.formatDate('dd/mm/yy', createdDate) + " " + h + ":" + m + ":" + s;

                $('td:eq(0)', nRow).html(dt_Created);

                $('td:eq(4)', nRow).html('<a href="/DocumentManagement/CustomerDocumentsView/' + aData.Id + '"target="_blank">' + aData.DocumentTypeDesc + '</a>');
                return nRow;
            },
            // Display settings
            "iDisplayLength": 100,
            "bJQueryUI": true,
            "aaSorting": [[0, "desc"]],
            "aoColumns": [
            { "mDataProp": "CreatedDate", "sTitle": "Created Date" },
            { "mDataProp": "Customer.FullName", "sTitle": "Customer Name", "sWidth": "12%" },
            { "mDataProp": "Customer.MobileNumber", "sTitle": "Customer Mobile No." },
            { "mDataProp": "Customer.IDNumber", "sTitle": "Customer IDNumber" },
            { "mDataProp": "DocumentTypeDesc", "sTitle": "DocumentTypeDesc" }],
        });
    });

</script>
<div>
    <fieldset>
        <legend>Documents for @customername</legend>
        <div><p><p> @Html.ActionLink("Upload Customer Documents", "UploadFile", "DocumentManagement",  new { id = @customerId }, new { @class = "classname" })</p></div>
        <table cellpadding="0" cellspacing="1" id="customerdocuments">
            <tbody>
                <tr>
                    <td colspan="7" class="dataTables_empty">
                        Loading data from server
                    </td>
                </tr>
            </tbody>
        </table>
        <div></div>
    </fieldset>
</div>

<style>
    a.classname {
        background-color: #d3dce0;
        border: 1px solid #787878;
        text-decoration: none;
        cursor: pointer;
        font-size: 1.1em;
        border-radius: 3px;
        font-weight: 600;
        padding: 7px;
        margin-right: 8px;
        width: auto;
    }
</style>

Nikopeshe.WebApplication_Backup_2016.08.02_01.18.59/Views/DocumentManagement/Index.cshtml
@model IEnumerable<Nikopeshe.Entity.DataModels.CustomerDocument>

@@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DocumentTypeDesc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DocumentTypeDesc)
            </td>
            <td>
                @{
        var base64 = Convert.ToBase64String(item.Image ?? item.Image);
        var imgSrc = String.Format("data:application/pdf;base64,{0}", base64);
                }
                <img src="@imgSrc" style="max-height:250px" />
            </td>
        </tr>
    }

</table>

Nikopeshe.WebApplication_Backup_2016.08.02_01.18.59/Views/DocumentManagement/LoanRequestDocuments.cshtml
@using Nikopeshe.Entity.DataModels
@using Nikopeshe.WebApplication.Controllers
@using Microsoft.Web.Mvc
@using Nikopeshe.WebApplication.Extensions
@{
    ViewBag.Title = "Loan Application Documents";

    string header = ViewBag.Header as string;

    var id = ViewBag.Id;

    var customername = ViewBag.CustomerFullName as string;
    var loanreferencenumber = ViewBag.LoanRefNo as string;
    
}

<h2>
    @Html.Raw(header)
</h2>

<script type="text/javascript">
    $(document).ready(function () {

        $('#loanapplicationdocuments').dataTable({
            // Ajax settings
            "sPaginationType": "full_numbers",
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "@(Url.Action("GetLoanRequestDocuments", "DocumentManagement", new { id = id }))",
            "sServerMethod": "POST",
            // Callback settings
            "fnRowCallback": function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                /* row manipulation */

                var createdDate = new Date(parseInt(aData.CreatedDate.replace("/Date(", "").replace(")/", ""), 10));

                var h = ("0" + createdDate.getHours()).slice(-2);
                var m = ("0" + createdDate.getMinutes()).slice(-2);
                var s = ("0" + createdDate.getSeconds()).slice(-2);

                var dt_Created = $.datepicker.formatDate('dd/mm/yy', createdDate) + " " + h + ":" + m + ":" + s;

                $('td:eq(0)', nRow).html(dt_Created);

                $('td:eq(3)', nRow).html('<a href="/DocumentManagement/LoanRequestDocumentView/' + aData.Id + '"target="_blank">' + aData.DocumentTypeDesc + '</a>');
                return nRow;
            },
            // Display settings
            "iDisplayLength": 100,
            "bJQueryUI": true,
            "aaSorting": [[0, "desc"]],
            "aoColumns": [
            { "mDataProp": "CreatedDate", "sTitle": "Created Date" },
            { "mDataProp": "LoanRequest.CustomerAccount.Customer.FullName", "sTitle": "Customer Name", "bSortable": false  },
            { "mDataProp": "LoanRequest.LoanReferenceNumber", "sTitle": "Loan Ref No" },
            { "mDataProp": "DocumentTypeDesc", "sTitle": "DocumentType Desc" }],
        });
    });

</script>
<div>
    <fieldset>
        <legend>Documents for @customername, Loan Reference No @loanreferencenumber</legend>
        <div><p><p> @Html.ActionLink("Upload Loan Request Document", "UploadLoanApplicationDocuments", "DocumentManagement", new {@id = @id }, new { @class = "classname" })</p></div>
        <table cellpadding="0" cellspacing="1" id="loanapplicationdocuments">
            <tbody>
                <tr>
                    <td colspan="7" class="dataTables_empty">
                        Loading data from server
                    </td>
                </tr>
            </tbody>
        </table>
        <div></div>
    </fieldset>
</div>

<style> 
    a.classname {
        background-color: #d3dce0;
        border: 1px solid #787878;
        text-decoration: none;
        cursor: pointer;
        font-size: 1.1em;
        border-radius: 3px;
        font-weight: 600;
        padding: 7px;
        margin-right: 8px;
        width: auto;
    }
</style>

Nikopeshe.WebApplication_Backup_2016.08.02_01.18.59/Views/DocumentManagement/PDFPartialView.cshtml
<h4>Partial View That display PDF....</h4>

<embed src="/Temp.pdf" type="application/pdf"></embed>

Nikopeshe.WebApplication_Backup_2016.08.02_01.18.59/Views/DocumentManagement/UploadFile.cshtml
@model Nikopeshe.Entity.DataModels.CustomerDocument

@{
    ViewBag.Title = "Upload Document";

    //var customerlist = ViewBag.CustomerSelectList as List<SelectListItem>;

    var CustomerName = ViewBag.CustomerName as string;
    var mobilenunber = ViewBag.MobileNumber as string;
    var IdNumber = ViewBag.IdNumber as string;
}

@using (Html.BeginForm("UploadFile", "DocumentManagement", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>Upload Customer Documents</legend>
        @Html.ValidationSummary(false, "Operation was unsuccessful. Please correct the errors and try again.")
        <div class="editor-label">
            <b>@Html.Label("Customer Name")</b>
        </div>
        <div class="editor-label">
            @Html.DisplayName(@CustomerName)
        </div>

        <div class="editor-label">
            <b>@Html.Label("Mobile Number")</b>
        </div>
        <div class="editor-label">
            @Html.DisplayName(@mobilenunber)
        </div>

        <div class="editor-label">
            <b>@Html.Label("ID Number")</b>
        </div>
        <div class="editor-label">
            @Html.DisplayName(@IdNumber)
        </div>

        @*<div class="editor-label">
            <b>@Html.LabelFor(model => model.CustomerId)</b>
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.CustomerId, customerlist)
            @Html.ValidationMessageFor(model => model.CustomerId)
        </div>*@

        <div class="editor-label">
            <b>@Html.LabelFor(model => model.DocumentType)</b>
        </div>
        <div class="editor-field">
            @Html.EnumDropDownListFor(model => model.DocumentType, "Select Document Type")
            @Html.ValidationMessageFor(model => model.DocumentType)
        </div>

        <div class="editor-field">
            <input type="file" name="PostedFile" />            
        </div>

        <div class="editor-field"><input type="submit" value="Upload" class="btn btn-default" /></div>
    </fieldset>
}


Nikopeshe.WebApplication_Backup_2016.08.02_01.18.59/Views/DocumentManagement/UploadLoanApplicationDocuments.cshtml
@model Nikopeshe.Entity.DataModels.LoanRequestDocument

@{
    ViewBag.Title = "Upload Document";

    var customerlist = ViewBag.CustomerSelectList as List<SelectListItem>;

    var customerName = ViewBag.CustomerName as string;
    var LoanAmount = ViewBag.LoanAmount as string;
    var amount = decimal.Parse(LoanAmount);
    decimal value = Math.Round(amount, 0);
    var result = string.Concat(value);
    var LoanReferenceNumber = ViewBag.LoanReferenceNumber as string;
}

@*<script type="text/jscript">
    $(function () {
        $('#customerselectlist').change(function () {
            $.getJSON('/DocumentManagement/CustomerLoanSelectList/' + $('#customerselectlist').val(), function (data) {
                var items = null;
                $.each(data, function (i, state) {
                    items += "<option value='" + state.Value + "'>" + state.Text + "</option>";
                });
                $('#LoanRequestId').html(items);
            });
        });
    });
</script>*@

@using (Html.BeginForm("UploadLoanApplicationDocuments", "DocumentManagement", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>Upload Loan Request Documents for @customerName</legend>
        @Html.ValidationSummary(false, "Operation was unsuccessful. Please correct the errors and try again.")
        @*<div class="editor-label">
            <b>@Html.Label("Customer Name")</b>
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.CustomerId, customerlist, new { id = "customerselectlist" }))
            @Html.ValidationMessageFor(model => model.CustomerId)
        </div>*@

        @*<div class="editor-label">
            @Html.LabelFor(model => model.LoanRequestId)
        </div>
        <div class="editor-field">
            <select id="LoanRequestId" name="loanrequest"></select><br />
            @Html.ValidationMessageFor(model => model.LoanRequestId)
        </div>*@

        <div class="editor-label">
            <b>@Html.Label("Customer Name")</b>
        </div>
        <div class="editor-field">
            @Html.DisplayName(@customerName)            
        </div>

        <div class="editor-label">
            <b>@Html.Label("Loan Reference Number")</b>
        </div>
        <div class="editor-field">
            @Html.DisplayName(@LoanReferenceNumber)
        </div>

        <div class="editor-label">
            <b>@Html.Label("Loan Amount")</b>
        </div>
        <div class="editor-field">
            @Html.DisplayName(@result)
        </div>

        <div class="editor-label">
            <b>@Html.LabelFor(model => model.DocumentType)</b>
        </div>
        <div class="editor-field">
            @Html.EnumDropDownListFor(model => model.DocumentType, "Select Document Type")
            @Html.ValidationMessageFor(model => model.DocumentType)
        </div>

        <div class="editor-field">
            <input type="file" name="PostedFile" />
        </div>

        <div class="editor-field"><input type="submit" value="Upload" class="btn btn-default" /></div>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Customer")
</div>

Nikopeshe.WebApplication_Backup_2016.08.02_01.18.59/Views/DocumentManagement/UploadSuccess.cshtml
@{
    ViewBag.Title = "Upload Successful";
}
<fieldset>
    <legend>Upload Successful</legend>
    The document was uploaded successfully.    
</fieldset>

